### ISSUE TITLE
Items disappearing and can't pull items out of the system

### ISSUE THREAD

**Issue by MrTubzy456** [MrRiegel/Storage-Network#45] opened 2016-06-03 03:00 UTC
Like it says in the title, I have items disappearing in my system. I noticed when I had to make a second trip to the nether for glowstone. After that trip I put half a stack of glowstone in the system and checked a minute later and it was gone.

Also, I have Blood Magic items in there that I just can't pull out of the system. I've tried left-clicking, right-clicking, and shift+clicking on both and those items just won't come out of the system.

**Comment by MrTubzy456** [comment] 2016-06-03 03:00
StorageNetwork-1.9.4-1.11.1.jar that's the version.

**Comment by KidsDontPlay** [comment] 2016-06-03 08:02
what kind of storage do you use?

**Comment by MrTubzy456** [comment] 2016-06-03 13:26
I'm using Storage drawers for large quantity items like ingots and cobble. I actually took everything out of the system and I noticed a lot of things had disappeared. Items from vanilla, iron chests, blood magic, and more. I kept an eye on it to see if it was just a mod interaction thing but it doesn't seem to be that.

**Comment by MrTubzy456** [comment] 2016-06-03 14:01
Also, I want to add onto this as I just thought of it. Before I posted the issue I added empty storage drawers to the system. I wanted to see if the system was trying to put items into the drawers and that maybe the items were caught in some weird limbo. Nothing showed up in the drawers though.

**Comment by KidsDontPlay** [comment] 2016-06-03 21:59
Mmh.. that's pretty tricky. I cannot reproduce the problems. Neither the disappearing nor the problem with blood magic items.
Would you say that that is a problem with storage drawers?

**Comment by MrTubzy456** [comment] 2016-06-03 22:43
I can certainly try again without the pipe connected to the drawer controller again. If my stream video wasn't so long I could show you. I'll try it out again on cam and see if I can reproduce it. 

The blood magic item is a tartaric gem. It's still sitting in my storage network so I can definitely show that.

**Comment by MrTubzy456** [comment] 2016-06-03 23:20
I can't get this to reproduce either. I must have done something during my playthrough to trigger it. I can't figure out what I did. I tried with and without storage drawers attached and it's no triggering it to happen.

**Comment by MrTubzy456** [comment] 2016-06-12 14:49
Ok this happened to me again. It was glowstone again. This is on a different modpack that's on a server. I'll ask if anyone else has had the same issue.

Also, it seems that it has problems with items that have lost durability. That tartaric gem wasn't full when i couldn't pull it out. I accidentally threw my tinker's axe in there and couldn't get it back out for a few hours. And when I finally did get it out it duplicated.

**Comment by KidsDontPlay** [comment] 2016-06-12 17:55
Are you sure glowstone was ever in the network?
Maybe it was a problem with insertion.
If no, is the glowstone still in the connected chest and just invisible in the GUI?

**Comment by MrTubzy456** [comment] 2016-06-12 19:04
I actually put it straight into the request table both times. I opened the screen to the network and shift-right clicked it into the system. I know it's in there right because I use it while it's in there at first and then I come back a couple hours later and it's gone.

If it's connected to another system like storage drawers, it doesn't change a thing with them. They work fine. It's in the system that's giving me issues.

**Comment by KidsDontPlay** [comment] 2016-06-13 07:10
Was the chunk with the network unloaded between using the items and disapperaing?

**Comment by MrTubzy456** [comment] 2016-06-13 07:34
No. I'm using a chunk loader from extra utilities. By the way, this time it wasn't connected to anything.

**Comment by KidsDontPlay** [comment] 2016-06-13 13:09
what wasn't connected to anything?

**Comment by MrTubzy456** [comment] 2016-06-13 14:39
The storage network. The first time I ran into this issue it was connected to storage drawers. This time it was its own network and not connected to anything.

**Comment by KidsDontPlay** [comment] 2016-06-13 14:41
you mean item boxes?

**Comment by MrTubzy456** [comment] 2016-06-13 14:45
The first time it was connected to a controller from storage drawers. This time I had a small network using only your mod. This is in our multiplayer server on a new world.

Sorry about so many messages, I'm just trying to be as detailed as I can to help you figure out what's causing this.

**Comment by KidsDontPlay** [comment] 2016-06-13 18:53
Do the items sometime reappear or are they vanished for ever?

**Comment by MrTubzy456** [comment] 2016-06-13 21:56
Gone forever.

**Comment by xannor** [comment] 2016-06-19 15:47
I have noticed this as well, I have lost a golden lasso with a villager in it and other various items, I could swear I had, but I could not find.
I am currently using storage drawers for some items and item boxes for bulk. Prior I was using storage drawers and scattered vanilla chests. I noticed that sometimes the items in the chests would not show up on the network and I could not drop items in but had to shift click. My storage drawer setup is mainly farms and bulk items, though I do have multiple separate drawer controllers for the different farm groups.

I don't currently have a chunkloader but all of my network is within three chunk radius.

My thougths are that the network is possibly storing to an invalid location, but thinks it is valid so the item is never saved. Or there is a sync issue with the connectors and the item data is not getting sent to the storage on the other side due to tick lag or something similar.

**Comment by APolarBaer** [comment] 2016-07-06 02:45
i keep losing items aswell, 200 iron ingots, glowstone, magma cream, iron bars, ender pearls and a bunch of other stuff, twice in the same session..  
using just the storage network items to store them

**Comment by KidsDontPlay** [comment] 2016-07-06 16:02
Ok guys.
I guess I found the bug.
At least the reason for the item losing.
I will make some tests and release the (hopefully) fixed version asap

**Comment by KidsDontPlay** [comment] 2016-07-06 21:37
I close this issue now.
If you still have that bug I will reopen it.

**Closed as completed by KidsDontPlay** 2016-07-06 21:37 UTC
