### ISSUE TITLE
[DEV] Stock upgrade.

### ISSUE THREAD

**Issue by MrGraphic** [MrRiegel/Storage-Network#9] opened 2016-02-12 17:42 UTC
Just tried, fantastic. 
I think that making it work with " Operational " would extend greatly functionality towards precision uses.
Same goes for defining the number of items. Instead of a global value let users define each item separately by modifying number of items in filter slots for example. - yeah, that would make it work together without gui clutter and modyfications.
I hope you will not hate me @MrRiegel for all these suggestions :sweat_smile:

**Comment by KidsDontPlay** [comment] 2016-02-12 18:51
Did you build the mod by yourself? Interesting.
the problem with modifying the number in the slots is that the maximum is 64.

**Comment by MrGraphic** [comment] 2016-02-12 19:59
To be honest compiling from source never been easier thanks to gradle. If the repo is configured properly then just clone and run "gradel build" - soooo easy compared to old times :smiley: 

Unforunelly I have limited knowledge on how to change max ( vanilla ) stack size for specific case.  I saw many examples in mods but never saw code behind that feature. Well maybe once in [BloodMagic](https://github.com/WayofTime/BloodMagic.git) repo.

**Comment by KidsDontPlay** [comment] 2016-02-13 01:08
well, the new commit is online, your honor.
you can compile.
warning: all cable filters will be reset.

**Comment by MrGraphic** [comment] 2016-02-13 14:21
Ok, I compiled and tested.
I was going to write that this commit totally broke mechanics but I saw that you just pushed a fix.
I did excesive testing on vanilla inventories and Buildcraft ones, what I have found:
- operational and stock doesn't work together - you can't put both in one cable
- when there is no valid/empty space in destination inventory or there is already other item but with a diffrent meta and you set cable to ignore meta data, cable will void all items in network within meta range trying to put that item in destination inventory - tested only on export cable connected to vanilla furnace, chests and BC's auto workbench, with and without stock upgrade.
- very minor rendering glitch where items render behind "highlight" box in filter slots.

Sorry, I wasn't able to try this earlier.

**Comment by MrRiegel** [comment] 2016-02-13 22:22
> operational and stock doesn't work together - you can't put both in one cable<

**Comment by KidsDontPlay** [comment] 2016-02-13 22:28
thank you for being my tester

> operational and stock doesn't work together - you can't put both in one cable

this was intended. but actually i could make them compatible.

I'll fix the bugs tomorrow.
btw: what time zone are you in?

**Comment by MrGraphic** [comment] 2016-02-13 22:36
I'm glad I can help and I'm honored :smile: 
I though it was intended.
Actually I'm in in UTC+0.

**Comment by KidsDontPlay** [comment] 2016-02-14 13:13
so, should be fixed.
did you notice, that you can delete a filter slot by clicking with mouse wheel and increase/decrease the number in slot by 10 while holding shift?

you can test the mod with "gradle runClient" too.

<del>if you give me you curseforge name I could credit you as tester</del>

Gotcha

**Comment by MrGraphic** [comment] 2016-02-14 13:42
I just saw, cool :smiley: 
Yup, noticed shift click right away but missed that middle click - was going to sugest slot reset :).
Usually I'm testing in non-dev enviroment. There is a reason for that and this is perfect example :wink: 
https://gist.github.com/MrGraphic/fe3d27d0e2115232e057
Of course works in dev.

**Comment by MrGraphic** [comment] 2016-02-14 14:11
Ok, tested most of the stuff in dev instance - seems to be all ok. Feels solid and fleshed out :).

**Closed as completed** 2016-02-14 14:45 UTC

**Comment by MrGraphic** [comment] 2016-02-14 15:19
Just so you know. There was something not clear for me so I recompiled project and it seems to be working in non dev without issues - apparently something gone wrong during packaging.
